apiVersion: v1
kind: Pod
spec:
  containers:  
    - name: agent
      image: registry.crazyzone.be/jenkins-agent:latest
      command: ["tail", "-f", "/dev/null"] 
      imagePullPolicy: Always
      volumeMounts:
        - name: docker
          mountPath: /var/run/docker.sock # We use the k8s host docker engine
  volumes:
    - name: docker
      hostPath:
        path: /var/run/docker.sock